name: go-bot
services:
  database:
    container_name: postgres
    image: "postgres:16.3-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  queue:
    container_name: rabbitmq
    image: rabbitmq:3.13.3-management
    ports:
      - 5672:5672
      - 15672:15672
  s3:
    container_name: minio
    image: bitnami/minio:2024.6.13
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
